---
# handlers file for modjk_role
    - name : restart httpd
      service:
        name: httpd
        state: restarted #to restart
        enabled: yes

    - name: restart tomcat
      shell: "{{ tomcat_home }}/bin/shutdown.sh"
      shell: "{{ tomcat_home }}/bin/startup.sh"
